import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SPEC_URL = `${API_URL}/docs/json`;

const here = dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = resolve(here, "../src/shared/api/generated");
const DOCS_PATH = resolve(GENERATED_DIR, "openapi.json");
const TYPES_PATH = resolve(GENERATED_DIR, "schema.d.ts");

const HEADER = [
  "/* eslint-disable */",
  "// AUTO-GENERATED by `npm run openapi:generate` — do not edit by hand.",
  `// Source: ${SPEC_URL}`,
  "",
].join("\n");

function fail(message) {
  console.error(`\n✖ openapi:generate failed\n  ${message}\n`);
  process.exit(1);
}

let docs;
try {
  const res = await fetch(SPEC_URL);
  if (!res.ok) {
    fail(`Backend responded ${res.status} ${res.statusText} at ${SPEC_URL}.`);
  }
  docs = await res.json();
} catch (err) {
  fail(
    `Backend unreachable at ${SPEC_URL}.\n` +
      `  Start it with \`npm run server\` in app/backend (dev port 3000), ` +
      `or set API_URL to its origin.\n` +
      `  (${err instanceof Error ? err.message : String(err)})`,
  );
}

await mkdir(GENERATED_DIR, { recursive: true });
await writeFile(DOCS_PATH, `${JSON.stringify(docs, null, 2)}\n`, "utf8");

const ast = await openapiTS(docs);
await writeFile(TYPES_PATH, `${HEADER}${astToString(ast)}`, "utf8");

console.log(
  `✔ openapi:generate\n  docs   → ${DOCS_PATH}\n  types  → ${TYPES_PATH}`,
);
