name: phyzio

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: phyzio_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: phyzio_cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres


volumes:
  postgres_data:
  cloudbeaver_data:
