export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  USERS: "/users",
  USER_ITEM: "/users/:id",
  THERAPISTS: "/therapists",
  THERAPIST_ITEM: "/therapists/:id",
  CLIENTS: "/clients",
  CLIENT_ITEM: "/clients/:id",
  TREATMENTS: "/treatments",
  TREATMENT_ITEM: "/treatments/:id",
  TREATMENT_PLANS: "/treatment-plans",
  TREATMENT_PLAN_ITEM: "/treatment-plans/:id",
  SETTINGS: "/settings",
} as const;
